import { User, Post, Problem, Connection, Message, Conversation, Notification, LeaderboardEntry, Submission } from '@/types';

// Mock Users (5 realistic developers)
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    username: 'sarahchen',
    email: 'sarah@example.com',
    bio: 'Full-stack developer | React & Node.js enthusiast | Building scalable web apps',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1200&h=300&fit=crop',
    location: 'San Francisco, CA',
    website: 'https://sarahchen.dev',
    github: 'https://github.com/sarahchen',
    linkedin: 'https://linkedin.com/in/sarahchen',
    role: 'USER',
    xp: 15420,
    rank: 1,
    streak: 45,
    problemsSolved: 287,
    acceptanceRate: 89,
    skills: ['React', 'TypeScript', 'Node.js', 'PostgreSQL', 'Docker'],
    interests: ['Web Development', 'System Design', 'AI/ML'],
    isAvailableForConnection: true,
    isOnline: true,
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    name: 'Alex Kumar',
    username: 'alexkumar',
    email: 'alex@example.com',
    bio: 'Backend engineer specializing in microservices | Cloud architecture | Open source contributor',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Alex',
    location: 'Bangalore, India',
    website: 'https://alexkumar.tech',
    github: 'https://github.com/alexkumar',
    linkedin: 'https://linkedin.com/in/alexkumar',
    role: 'USER',
    xp: 12850,
    rank: 2,
    streak: 32,
    problemsSolved: 234,
    acceptanceRate: 85,
    skills: ['Java', 'Spring Boot', 'Kubernetes', 'AWS', 'MongoDB'],
    interests: ['Backend Development', 'DevOps', 'Distributed Systems'],
    isAvailableForConnection: true,
    isOnline: true,
    createdAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: '3',
    name: 'Emma Rodriguez',
    username: 'emmarodriguez',
    email: 'emma@example.com',
    bio: 'Frontend wizard ✨ | CSS animations lover | Building beautiful UIs',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Emma',
    location: 'Barcelona, Spain',
    website: 'https://emmarodriguez.design',
    github: 'https://github.com/emmarodriguez',
    linkedin: 'https://linkedin.com/in/emmarodriguez',
    role: 'USER',
    xp: 10200,
    rank: 3,
    streak: 28,
    problemsSolved: 189,
    acceptanceRate: 92,
    skills: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion', 'TypeScript'],
    interests: ['UI/UX', 'Web Animations', 'Design Systems'],
    isAvailableForConnection: false,
    isOnline: true,
    lastSeen: new Date('2024-11-25T10:30:00').toISOString(),
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    id: '4',
    name: 'Michael Zhang',
    username: 'michaelzhang',
    email: 'michael@example.com',
    bio: 'AI/ML Engineer | Python expert | Working on LLM applications',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Michael',
    location: 'Toronto, Canada',
    website: 'https://michaelzhang.ai',
    github: 'https://github.com/michaelzhang',
    linkedin: 'https://linkedin.com/in/michaelzhang',
    role: 'USER',
    xp: 9800,
    rank: 4,
    streak: 21,
    problemsSolved: 156,
    acceptanceRate: 88,
    skills: ['Python', 'TensorFlow', 'PyTorch', 'FastAPI', 'Docker'],
    interests: ['Machine Learning', 'NLP', 'Computer Vision'],
    isAvailableForConnection: true,
    isOnline: true,
    createdAt: new Date('2024-04-05').toISOString(),
  },
  {
    id: '5',
    name: 'Priya Sharma',
    username: 'priyasharma',
    email: 'priya@example.com',
    bio: 'Mobile dev | Flutter & React Native | Creating cross-platform magic 📱',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    location: 'Mumbai, India',
    website: 'https://priyasharma.dev',
    github: 'https://github.com/priyasharma',
    linkedin: 'https://linkedin.com/in/priyasharma',
    role: 'USER',
    xp: 8900,
    rank: 5,
    streak: 18,
    problemsSolved: 142,
    acceptanceRate: 86,
    skills: ['Flutter', 'React Native', 'Firebase', 'TypeScript', 'Dart'],
    interests: ['Mobile Development', 'UI/UX', 'Performance Optimization'],
    isAvailableForConnection: true,
    isOnline: true,
    createdAt: new Date('2024-05-12').toISOString(),
  },
];

// Mock Posts
export const mockPosts: Post[] = [
  {
    id: '1',
    content: 'Just finished implementing a real-time chat feature using Socket.IO and React Query! The combination of optimistic updates and real-time sync is 🔥\n\nKey learnings:\n- Use React Query mutations for instant UI updates\n- Socket.IO rooms for efficient message broadcasting\n- Proper error handling is crucial\n\nAnyone else working on similar features? Would love to discuss patterns!',
    authorId: '1',
    author: mockUsers[0],
    visibility: 'PUBLIC',
    reactionCount: 24,
    commentCount: 8,
    shareCount: 3,
    reactions: [],
    createdAt: new Date('2024-11-26T14:30:00').toISOString(),
    updatedAt: new Date('2024-11-26T14:30:00').toISOString(),
  },
  {
    id: '2',
    content: 'Excited to share my latest open-source project! 🎉\n\nBuilt a lightweight microservices monitoring dashboard with real-time metrics visualization. Tech stack:\n- Spring Boot for services\n- Prometheus for metrics\n- Grafana for dashboards\n- Kubernetes for orchestration\n\nCheck it out on GitHub and let me know what you think!',
    authorId: '2',
    author: mockUsers[1],
    visibility: 'PUBLIC',
    reactionCount: 42,
    commentCount: 15,
    shareCount: 12,
    reactions: [],
    createdAt: new Date('2024-11-26T10:15:00').toISOString(),
    updatedAt: new Date('2024-11-26T10:15:00').toISOString(),
  },
  {
    id: '3',
    content: 'CSS tip of the day! 💡\n\nDid you know you can create smooth scroll animations with just CSS?\n\n```css\nhtml {\n  scroll-behavior: smooth;\n}\n```\n\nCombine with scroll-margin-top for perfect nav offset!\n\nWhat are your favorite CSS tricks?',
    authorId: '3',
    author: mockUsers[2],
    visibility: 'PUBLIC',
    reactionCount: 67,
    commentCount: 23,
    shareCount: 18,
    reactions: [],
    createdAt: new Date('2024-11-25T16:45:00').toISOString(),
    updatedAt: new Date('2024-11-25T16:45:00').toISOString(),
  },
  {
    id: '4',
    content: 'Fascinating discovery in my ML project today!\n\nBy fine-tuning a BERT model on domain-specific data, I improved accuracy from 78% to 94%. The key was:\n\n1. High-quality labeled dataset\n2. Learning rate scheduling\n3. Early stopping to prevent overfitting\n\nNLP is getting more exciting every day! 🚀',
    authorId: '4',
    author: mockUsers[3],
    visibility: 'PUBLIC',
    reactionCount: 31,
    commentCount: 12,
    shareCount: 7,
    reactions: [],
    createdAt: new Date('2024-11-25T11:20:00').toISOString(),
    updatedAt: new Date('2024-11-25T11:20:00').toISOString(),
  },
  {
    id: '5',
    content: 'Looking for developers interested in contributing to a new open-source Flutter UI kit! 📱\n\nWe are building a comprehensive component library with:\n- 50+ customizable widgets\n- Dark/light theme support\n- Accessibility built-in\n- Extensive documentation\n\nDM me if you want to join!',
    authorId: '5',
    author: mockUsers[4],
    visibility: 'PUBLIC',
    reactionCount: 38,
    commentCount: 19,
    shareCount: 11,
    reactions: [],
    createdAt: new Date('2024-11-24T13:00:00').toISOString(),
    updatedAt: new Date('2024-11-24T13:00:00').toISOString(),
  },
];

// Mock Problems
export const mockProblems: Problem[] = [
  {
    id: '1',
    title: 'Two Sum',
    slug: 'two-sum',
    description: 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.',
    difficulty: 'EASY',
    category: 'DSA',
    tags: ['Array', 'Hash Table'],
    constraints: '2 <= nums.length <= 10^4',
    examples: 'Input: nums = [2,7,11,15], target = 9\nOutput: [0,1]\nExplanation: Because nums[0] + nums[1] == 9, we return [0, 1].',
    xpReward: 10,
    acceptanceRate: 49,
    totalSubmissions: 15420,
    isSolved: true,
    createdAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    description: 'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.',
    difficulty: 'EASY',
    category: 'DSA',
    tags: ['String', 'Stack'],
    constraints: '1 <= s.length <= 10^4',
    xpReward: 10,
    acceptanceRate: 40,
    totalSubmissions: 12890,
    isSolved: false,
    createdAt: new Date('2024-01-02').toISOString(),
  },
  {
    id: '3',
    title: 'Merge Two Sorted Lists',
    slug: 'merge-two-sorted-lists',
    description: 'You are given the heads of two sorted linked lists list1 and list2.\n\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\n\nReturn the head of the merged linked list.',
    difficulty: 'EASY',
    category: 'DSA',
    tags: ['Linked List', 'Recursion'],
    constraints: 'The number of nodes in both lists is in the range [0, 50].',
    xpReward: 10,
    acceptanceRate: 62,
    totalSubmissions: 10234,
    isSolved: true,
    createdAt: new Date('2024-01-03').toISOString(),
  },
  {
    id: '4',
    title: 'Maximum Subarray',
    slug: 'maximum-subarray',
    description: 'Given an integer array nums, find the subarray with the largest sum, and return its sum.',
    difficulty: 'MEDIUM',
    category: 'DSA',
    tags: ['Array', 'Dynamic Programming'],
    constraints: '1 <= nums.length <= 10^5',
    xpReward: 20,
    acceptanceRate: 50,
    totalSubmissions: 18750,
    isSolved: false,
    createdAt: new Date('2024-01-04').toISOString(),
  },
  {
    id: '5',
    title: 'Binary Tree Level Order Traversal',
    slug: 'binary-tree-level-order-traversal',
    description: 'Given the root of a binary tree, return the level order traversal of its nodes values. (i.e., from left to right, level by level).',
    difficulty: 'MEDIUM',
    category: 'DSA',
    tags: ['Tree', 'BFS', 'Binary Tree'],
    constraints: 'The number of nodes in the tree is in the range [0, 2000].',
    xpReward: 20,
    acceptanceRate: 64,
    totalSubmissions: 14560,
    isSolved: true,
    createdAt: new Date('2024-01-05').toISOString(),
  },
  {
    id: '6',
    title: 'Implement Debounce Function',
    slug: 'implement-debounce',
    description: 'Implement a debounce function in JavaScript that limits the rate at which a function can fire.\n\nThe debounced function should delay invoking func until after wait milliseconds have elapsed since the last time the debounced function was invoked.',
    difficulty: 'MEDIUM',
    category: 'JavaScript',
    tags: ['JavaScript', 'Closures', 'Timers'],
    xpReward: 25,
    acceptanceRate: 55,
    totalSubmissions: 8934,
    isSolved: false,
    createdAt: new Date('2024-01-06').toISOString(),
  },
  {
    id: '7',
    title: 'Design REST API',
    slug: 'design-rest-api',
    description: 'Design a RESTful API for a blog platform. Include endpoints for:\n- User authentication\n- CRUD operations for blog posts\n- Comments on posts\n- User profiles\n\nDescribe the HTTP methods, endpoints, request/response formats, and status codes.',
    difficulty: 'MEDIUM',
    category: 'APIs',
    tags: ['REST API', 'System Design', 'HTTP'],
    xpReward: 30,
    acceptanceRate: 45,
    totalSubmissions: 6721,
    isSolved: false,
    createdAt: new Date('2024-01-07').toISOString(),
  },
  {
    id: '8',
    title: 'LRU Cache Implementation',
    slug: 'lru-cache',
    description: 'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRUCache class with get and put methods. Both operations should run in O(1) time complexity.',
    difficulty: 'HARD',
    category: 'DSA',
    tags: ['Hash Table', 'Linked List', 'Design'],
    xpReward: 40,
    acceptanceRate: 38,
    totalSubmissions: 11234,
    isSolved: false,
    createdAt: new Date('2024-01-08').toISOString(),
  },
];

// Mock Leaderboard
export const mockLeaderboard: LeaderboardEntry[] = mockUsers.map((user, index) => ({
  rank: user.rank,
  user,
  xp: user.xp,
  problemsSolved: user.problemsSolved,
  streak: user.streak,
  acceptanceRate: user.acceptanceRate,
}));

// Mock Connections
export const mockConnections: Connection[] = [
  {
    id: '1',
    requesterId: '1',
    requester: mockUsers[0],
    addresseeId: '2',
    addressee: mockUsers[1],
    status: 'ACCEPTED',
    createdAt: new Date('2024-10-15').toISOString(),
    updatedAt: new Date('2024-10-15').toISOString(),
  },
  {
    id: '2',
    requesterId: '1',
    requester: mockUsers[0],
    addresseeId: '3',
    addressee: mockUsers[2],
    status: 'ACCEPTED',
    createdAt: new Date('2024-10-20').toISOString(),
    updatedAt: new Date('2024-10-20').toISOString(),
  },
  {
    id: '3',
    requesterId: '4',
    requester: mockUsers[3],
    addresseeId: '1',
    addressee: mockUsers[0],
    status: 'PENDING',
    createdAt: new Date('2024-11-25').toISOString(),
    updatedAt: new Date('2024-11-25').toISOString(),
  },
];

// Mock Conversations
export const mockConversations: Conversation[] = [
  {
    id: '1',
    participants: [mockUsers[0], mockUsers[1]],
    lastMessage: {
      id: '1',
      senderId: '2',
      sender: mockUsers[1],
      receiverId: '1',
      receiver: mockUsers[0],
      content: 'Hey! Want to pair program on that microservices project?',
      type: 'TEXT',
      isRead: false,
      isEdited: false,
      createdAt: new Date('2024-11-26T15:30:00').toISOString(),
      updatedAt: new Date('2024-11-26T15:30:00').toISOString(),
    },
    unreadCount: 1,
    createdAt: new Date('2024-10-15').toISOString(),
    updatedAt: new Date('2024-11-26T15:30:00').toISOString(),
  },
  {
    id: '2',
    participants: [mockUsers[0], mockUsers[2]],
    lastMessage: {
      id: '2',
      senderId: '1',
      sender: mockUsers[0],
      receiverId: '3',
      receiver: mockUsers[2],
      content: 'Thanks for the CSS tip! Really helpful 🙌',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date('2024-11-25T17:00:00').toISOString(),
      updatedAt: new Date('2024-11-25T17:00:00').toISOString(),
    },
    unreadCount: 0,
    createdAt: new Date('2024-10-20').toISOString(),
    updatedAt: new Date('2024-11-25T17:00:00').toISOString(),
  },
];

// Mock Notifications
export const mockNotifications: Notification[] = [
  {
    id: '1',
    userId: '1',
    type: 'CONNECTION_REQUEST',
    title: 'New Connection Request',
    message: 'Michael Zhang wants to connect with you',
    link: '/connections',
    isRead: false,
    metadata: { userId: '4' },
    createdAt: new Date('2024-11-25T14:30:00').toISOString(),
  },
  {
    id: '2',
    userId: '1',
    type: 'POST_REACTION',
    title: 'Someone liked your post',
    message: 'Alex Kumar reacted to your post about Socket.IO',
    link: '/posts/1',
    isRead: false,
    createdAt: new Date('2024-11-26T10:20:00').toISOString(),
  },
  {
    id: '3',
    userId: '1',
    type: 'COMMENT',
    title: 'New Comment',
    message: 'Emma Rodriguez commented on your post',
    link: '/posts/1',
    isRead: true,
    createdAt: new Date('2024-11-25T16:50:00').toISOString(),
  },
  {
    id: '4',
    userId: '1',
    type: 'ACHIEVEMENT',
    title: '🏆 Achievement Unlocked!',
    message: 'You solved 250 problems! Keep it up!',
    isRead: true,
    createdAt: new Date('2024-11-24T09:00:00').toISOString(),
  },
];

// Current logged-in user
export const currentUser = mockUsers[0];

// Helper function to get mock data
export const getMockData = () => ({
  users: mockUsers,
  currentUser,
  posts: mockPosts,
  problems: mockProblems,
  leaderboard: mockLeaderboard,
  connections: mockConnections,
  conversations: mockConversations,
  notifications: mockNotifications,
});
