import {
  User,
  Post,
  Problem,
  Connection,
  Message,
  Conversation,
  Notification,
  LeaderboardEntry,
  Submission,
  Achievement,
  CollaborationSession,
  SavedItem,
  ActivityFeedItem,
} from '@/types';

// ============================================================
// USERS (matching backend User + UserProfile + Gamification)
// ============================================================
export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sarah Chen',
    username: 'saranchen',
    email: 'sarah@example.com',
    bio: 'Senior Full-Stack Architect | Distributed systems, React & Go | Open source maintainer 🚀',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=256&h=256&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=1400&h=350&fit=crop',
    location: 'San Francisco, CA',
    website: 'https://sarahchen.dev',
    github: 'https://github.com/sarahchen',
    linkedin: 'https://linkedin.com/in/sarahchen',
    twitter: 'https://twitter.com/sarahcodes',
    role: 'USER',
    developerLevel: 'ARCHITECT',
    currentRole: 'Staff Software Engineer',
    company: 'Vercel / Next.js Contributor',
    xp: 15420,
    rank: 1,
    streak: 45,
    problemsSolved: 287,
    acceptanceRate: 89,
    skills: ['React', 'TypeScript', 'Node.js', 'Go', 'PostgreSQL', 'Docker', 'GraphQL'],
    interests: ['System Design', 'Compiler Architecture', 'Distributed Databases'],
    isAvailableForConnection: true,
    isOnline: true,
    isLive: true,
    currentActivity: 'Building real-time collaborative code editor engine in WebAssembly',
    codingLanguage: 'TypeScript',
    liveNote: 'Working on OT algorithm. Feel free to join or ask questions!',
    createdAt: new Date('2024-01-15').toISOString(),
  },
  {
    id: '2',
    name: 'Alex Kumar',
    username: 'alexkumar',
    email: 'alex@example.com',
    bio: 'Lead Backend Engineer | High-throughput microservices, Kubernetes & Kafka fanatic',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=256&h=256&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=1400&h=350&fit=crop',
    location: 'Bangalore, India',
    website: 'https://alexkumar.tech',
    github: 'https://github.com/alexkumar',
    linkedin: 'https://linkedin.com/in/alexkumar',
    role: 'USER',
    developerLevel: 'LEAD',
    currentRole: 'Backend Lead',
    company: 'Stripe Ecosystem Partner',
    xp: 12850,
    rank: 2,
    streak: 32,
    problemsSolved: 234,
    acceptanceRate: 85,
    skills: ['Java', 'Spring Boot', 'Kubernetes', 'AWS', 'Kafka', 'Redis', 'PostgreSQL'],
    interests: ['High Concurrency', 'Event-Driven Architecture', 'Cloud Reliability'],
    isAvailableForConnection: true,
    isOnline: true,
    isLive: true,
    currentActivity: 'Benchmarking Redis vs KeyDB cache pipelines under 100k req/sec',
    codingLanguage: 'Go',
    liveNote: 'Reviewing PRs & benchmarking caching layers. Pair with me!',
    createdAt: new Date('2024-02-01').toISOString(),
  },
  {
    id: '3',
    name: 'Emma Rodriguez',
    username: 'emmarodriguez',
    email: 'emma@example.com',
    bio: 'Design Systems Lead & Frontend Sorceress ✨ | Tailwind, Framer Motion & WebGL wizardry',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=256&h=256&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=1400&h=350&fit=crop',
    location: 'Barcelona, Spain',
    website: 'https://emmarodriguez.design',
    github: 'https://github.com/emmarodriguez',
    linkedin: 'https://linkedin.com/in/emmarodriguez',
    role: 'USER',
    developerLevel: 'SENIOR',
    currentRole: 'Senior Frontend Engineer',
    company: 'Figma Community Plugin Creator',
    xp: 10200,
    rank: 3,
    streak: 28,
    problemsSolved: 189,
    acceptanceRate: 92,
    skills: ['React', 'Next.js', 'Tailwind CSS', 'Framer Motion', 'Three.js', 'TypeScript'],
    interests: ['Design Systems', 'Micro-Interactions', 'Creative Coding'],
    isAvailableForConnection: true,
    isOnline: true,
    isLive: true,
    currentActivity: 'Refactoring 3D shader canvas interactions with Three.js',
    codingLanguage: 'JavaScript',
    liveNote: 'Happy to give UI/UX and CSS animation feedback to anyone building!',
    createdAt: new Date('2024-03-10').toISOString(),
  },
  {
    id: '4',
    name: 'Michael Zhang',
    username: 'michaelzhang',
    email: 'michael@example.com',
    bio: 'AI/ML Systems Researcher | Building local LLM agents & fine-tuning pipelines',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=256&h=256&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1400&h=350&fit=crop',
    location: 'Toronto, Canada',
    website: 'https://michaelzhang.ai',
    github: 'https://github.com/michaelzhang',
    linkedin: 'https://linkedin.com/in/michaelzhang',
    role: 'USER',
    developerLevel: 'SENIOR',
    currentRole: 'Machine Learning Engineer',
    company: 'Autonomous AI Labs',
    xp: 9800,
    rank: 4,
    streak: 21,
    problemsSolved: 156,
    acceptanceRate: 88,
    skills: ['Python', 'PyTorch', 'FastAPI', 'LangChain', 'Docker', 'CUDA'],
    interests: ['LLM Orchestration', 'Vector Embeddings', 'RAG Pipelines'],
    isAvailableForConnection: true,
    isOnline: true,
    isLive: false,
    currentActivity: 'Evaluating RAG retrieval accuracy with hybrid rerankers',
    codingLanguage: 'Python',
    createdAt: new Date('2024-04-05').toISOString(),
  },
  {
    id: '5',
    name: 'Priya Sharma',
    username: 'priyasharma',
    email: 'priya@example.com',
    bio: 'Cross-Platform Mobile Specialist | Flutter & React Native Core Contributor 📱',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=256&h=256&fit=crop&crop=face',
    coverImage: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=1400&h=350&fit=crop',
    location: 'Mumbai, India',
    website: 'https://priyasharma.dev',
    github: 'https://github.com/priyasharma',
    linkedin: 'https://linkedin.com/in/priyasharma',
    role: 'USER',
    developerLevel: 'MID',
    currentRole: 'Mobile Solutions Architect',
    company: 'Fintech Hub Global',
    xp: 8900,
    rank: 5,
    streak: 18,
    problemsSolved: 142,
    acceptanceRate: 86,
    skills: ['Flutter', 'React Native', 'Dart', 'Kotlin', 'Firebase', 'GraphQL'],
    interests: ['Mobile Performance', 'Offline-First Apps', 'Bluetooth Low Energy'],
    isAvailableForConnection: true,
    isOnline: true,
    isLive: true,
    currentActivity: 'Optimizing Flutter engine frame rendering for 120Hz displays',
    codingLanguage: 'Dart',
    liveNote: 'Working on mobile gesture navigation. Open to quick chat!',
    createdAt: new Date('2024-05-12').toISOString(),
  },
  {
    id: '6',
    name: 'David Lindqvist',
    username: 'dlindqvist',
    email: 'david@example.com',
    bio: 'Rust & Systems Engineer | High performance networking, Linux kernels and WebAssembly',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=256&h=256&fit=crop&crop=face',
    location: 'Stockholm, Sweden',
    github: 'https://github.com/dlindqvist',
    role: 'USER',
    developerLevel: 'PRINCIPAL',
    currentRole: 'Principal Systems Architect',
    company: 'EdgeCloud Technologies',
    xp: 8450,
    rank: 6,
    streak: 39,
    problemsSolved: 175,
    acceptanceRate: 91,
    skills: ['Rust', 'C++', 'Linux', 'WebAssembly', 'eBPF', 'Tokio'],
    interests: ['Systems Programming', 'Zero-Cost Abstractions', 'Network Security'],
    isAvailableForConnection: true,
    isOnline: true,
    isLive: true,
    currentActivity: 'Writing an asynchronous TCP proxy using Tokio in Rust',
    codingLanguage: 'Rust',
    liveNote: 'Streaming systems code. Feel free to ask Rust questions!',
    createdAt: new Date('2024-03-22').toISOString(),
  },
  {
    id: '7',
    name: 'Elena Rostova',
    username: 'erostova',
    email: 'elena@example.com',
    bio: 'Security Researcher & Cryptography dev | Zero-Knowledge proofs and smart contract audits',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=256&h=256&fit=crop&crop=face',
    location: 'Berlin, Germany',
    github: 'https://github.com/erostova',
    role: 'USER',
    developerLevel: 'SENIOR',
    currentRole: 'Lead Security Auditor',
    company: 'ZK Protocol Labs',
    xp: 7600,
    rank: 7,
    streak: 15,
    problemsSolved: 130,
    acceptanceRate: 83,
    skills: ['Solidity', 'Rust', 'Cryptography', 'Python', 'Go'],
    interests: ['ZK-SNARKs', 'Smart Contract Security', 'Privacy Tech'],
    isAvailableForConnection: false,
    isOnline: false,
    createdAt: new Date('2024-06-01').toISOString(),
  },
];

export const currentUser = mockUsers[0];

// ============================================================
// CODING PROBLEMS (matching backend Problem schema & enums)
// ============================================================
export const mockProblems: Problem[] = [
  {
    id: '1',
    title: 'Two Sum',
    slug: 'two-sum',
    description:
      'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.\n\nYou may assume that each input would have exactly one solution, and you may not use the same element twice.\n\nYou can return the answer in any order.',
    difficulty: 'EASY',
    type: 'CODING',
    category: 'DSA',
    tags: ['Array', 'Hash Table'],
    constraints: '2 <= nums.length <= 10^4\n-10^9 <= nums[i] <= 10^9\n-10^9 <= target <= 10^9',
    examples: 'Input: nums = [2,7,11,15], target = 9\nOutput: [0,1]\nExplanation: Because nums[0] + nums[1] == 9, we return [0, 1].',
    xpReward: 10,
    acceptanceRate: 49,
    totalSubmissions: 15420,
    isSolved: true,
    editorial: 'Use a hash map to look up complements in O(1) time while iterating through the array once.',
    createdAt: new Date('2024-01-01').toISOString(),
  },
  {
    id: '2',
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    description:
      'Given a string s containing just the characters "(", ")", "{", "}", "[" and "]", determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.',
    difficulty: 'EASY',
    type: 'CODING',
    category: 'DSA',
    tags: ['String', 'Stack'],
    constraints: '1 <= s.length <= 10^4\ns consists of parentheses only "()[]{}"',
    xpReward: 10,
    acceptanceRate: 40,
    totalSubmissions: 12890,
    isSolved: true,
    editorial: 'Utilize a stack to push opening brackets and pop matching pairs when encountering closing brackets.',
    createdAt: new Date('2024-01-02').toISOString(),
  },
  {
    id: '3',
    title: 'Merge Two Sorted Lists',
    slug: 'merge-two-sorted-lists',
    description:
      'You are given the heads of two sorted linked lists list1 and list2.\n\nMerge the two lists into one sorted list. The list should be made by splicing together the nodes of the first two lists.\n\nReturn the head of the merged linked list.',
    difficulty: 'EASY',
    type: 'CODING',
    category: 'DSA',
    tags: ['Linked List', 'Recursion'],
    constraints: 'The number of nodes in both lists is in the range [0, 50].',
    xpReward: 10,
    acceptanceRate: 62,
    totalSubmissions: 10234,
    isSolved: true,
    createdAt: new Date('2024-01-03').toISOString(),
  },
  {
    id: '4',
    title: 'Maximum Subarray (Kadane)',
    slug: 'maximum-subarray',
    description: 'Given an integer array nums, find the subarray with the largest sum, and return its sum.',
    difficulty: 'MEDIUM',
    type: 'CODING',
    category: 'DSA',
    tags: ['Array', 'Dynamic Programming', 'Divide and Conquer'],
    constraints: '1 <= nums.length <= 10^5\n-10^4 <= nums[i] <= 10^4',
    xpReward: 20,
    acceptanceRate: 50,
    totalSubmissions: 18750,
    isSolved: true,
    createdAt: new Date('2024-01-04').toISOString(),
  },
  {
    id: '5',
    title: 'Binary Tree Level Order Traversal',
    slug: 'binary-tree-level-order-traversal',
    description: 'Given the root of a binary tree, return the level order traversal of its nodes values (i.e. from left to right, level by level).',
    difficulty: 'MEDIUM',
    type: 'CODING',
    category: 'DSA',
    tags: ['Tree', 'BFS', 'Binary Tree'],
    constraints: 'The number of nodes in the tree is in the range [0, 2000].',
    xpReward: 20,
    acceptanceRate: 64,
    totalSubmissions: 14560,
    isSolved: true,
    createdAt: new Date('2024-01-05').toISOString(),
  },
  {
    id: '6',
    title: 'Implement Debounce Function',
    slug: 'implement-debounce',
    description:
      'Implement a debounce function in JavaScript/TypeScript that limits the rate at which a function can fire.\n\nThe debounced function should delay invoking func until after wait milliseconds have elapsed since the last time the debounced function was invoked.',
    difficulty: 'MEDIUM',
    type: 'CODING',
    category: 'JAVASCRIPT',
    tags: ['JavaScript', 'Closures', 'Timers', 'Async'],
    xpReward: 25,
    acceptanceRate: 55,
    totalSubmissions: 8934,
    isSolved: false,
    createdAt: new Date('2024-01-06').toISOString(),
  },
  {
    id: '7',
    title: 'Design Scalable Rate Limiter',
    slug: 'design-rate-limiter',
    description:
      'Design a distributed rate limiter that handles 50,000 requests/sec with Token Bucket or Sliding Window Log algorithms in Redis.\n\nSpecify data structures, failure modes, race condition mitigations, and latency trade-offs.',
    difficulty: 'HARD',
    type: 'SYSTEM_DESIGN',
    category: 'SYSTEM_DESIGN',
    tags: ['Redis', 'Distributed Systems', 'Concurrency', 'APIs'],
    xpReward: 40,
    acceptanceRate: 35,
    totalSubmissions: 5410,
    isSolved: false,
    createdAt: new Date('2024-01-07').toISOString(),
  },
  {
    id: '8',
    title: 'LRU Cache Implementation',
    slug: 'lru-cache',
    description:
      'Design a data structure that follows the constraints of a Least Recently Used (LRU) cache.\n\nImplement the LRUCache class with get and put methods. Both operations must run in O(1) time complexity.',
    difficulty: 'HARD',
    type: 'CODING',
    category: 'DSA',
    tags: ['Hash Table', 'Linked List', 'Design'],
    xpReward: 40,
    acceptanceRate: 38,
    totalSubmissions: 11234,
    isSolved: false,
    createdAt: new Date('2024-01-08').toISOString(),
  },
  {
    id: '9',
    title: 'Median of Two Sorted Arrays',
    slug: 'median-of-two-sorted-arrays',
    description:
      'Given two sorted arrays nums1 and nums2 of size m and n respectively, return the median of the two sorted arrays.\n\nThe overall run time complexity should be O(log (m+n)).',
    difficulty: 'EXPERT',
    type: 'CODING',
    category: 'DSA',
    tags: ['Binary Search', 'Divide and Conquer', 'Array'],
    xpReward: 50,
    acceptanceRate: 29,
    totalSubmissions: 8120,
    isSolved: false,
    createdAt: new Date('2024-01-09').toISOString(),
  },
  {
    id: '10',
    title: 'Custom Promise.allSettled Polyfill',
    slug: 'promise-allsettled-polyfill',
    description:
      'Implement a polyfill for Promise.allSettled without using the native Promise.allSettled implementation. Ensure all settled promises are correctly categorized with status and value/reason.',
    difficulty: 'MEDIUM',
    type: 'CODING',
    category: 'JAVASCRIPT',
    tags: ['JavaScript', 'Promises', 'Async/Await'],
    xpReward: 25,
    acceptanceRate: 58,
    totalSubmissions: 6710,
    isSolved: true,
    createdAt: new Date('2024-01-10').toISOString(),
  },
];

// ============================================================
// LEADERBOARD (matching backend RankingsService & Redis sets)
// ============================================================
export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    user: mockUsers[0], // Sarah Chen
    xp: 15420,
    weeklyXp: 1840,
    monthlyXp: 6200,
    level: 9,
    levelTitle: 'Architect',
    problemsSolved: 287,
    streak: 45,
    acceptanceRate: 89,
    badges: ['Top Grandmaster', 'Algorithm Ace', 'Code Streak 30'],
  },
  {
    rank: 2,
    user: mockUsers[1], // Alex Kumar
    xp: 12850,
    weeklyXp: 1560,
    monthlyXp: 5100,
    level: 8,
    levelTitle: 'Lead',
    problemsSolved: 234,
    streak: 32,
    acceptanceRate: 85,
    badges: ['System Builder', 'Speed Demon'],
  },
  {
    rank: 3,
    user: mockUsers[2], // Emma Rodriguez
    xp: 10200,
    weeklyXp: 1250,
    monthlyXp: 4300,
    level: 7,
    levelTitle: 'Senior',
    problemsSolved: 189,
    streak: 28,
    acceptanceRate: 92,
    badges: ['UI Wizard', 'CSS Ninja'],
  },
  {
    rank: 4,
    user: mockUsers[3], // Michael Zhang
    xp: 9800,
    weeklyXp: 980,
    monthlyXp: 3800,
    level: 7,
    levelTitle: 'Senior',
    problemsSolved: 156,
    streak: 21,
    acceptanceRate: 88,
    badges: ['ML Pioneer'],
  },
  {
    rank: 5,
    user: mockUsers[4], // Priya Sharma
    xp: 8900,
    weeklyXp: 850,
    monthlyXp: 3400,
    level: 6,
    levelTitle: 'Mid',
    problemsSolved: 142,
    streak: 18,
    acceptanceRate: 86,
    badges: ['Mobile Core'],
  },
  {
    rank: 6,
    user: mockUsers[5], // David Lindqvist
    xp: 8450,
    weeklyXp: 790,
    monthlyXp: 3100,
    level: 6,
    levelTitle: 'Mid',
    problemsSolved: 175,
    streak: 39,
    acceptanceRate: 91,
    badges: ['Rustacean Master'],
  },
  {
    rank: 7,
    user: mockUsers[6], // Elena Rostova
    xp: 7600,
    weeklyXp: 620,
    monthlyXp: 2850,
    level: 5,
    levelTitle: 'Junior',
    problemsSolved: 130,
    streak: 15,
    acceptanceRate: 83,
    badges: ['Security Guardian'],
  },
];

// ============================================================
// LIVE DEVELOPERS & COLLABORATION ROOMS (backend LiveDeveloper)
// ============================================================
export const mockCollaborationSessions: CollaborationSession[] = [
  {
    id: 'room-1',
    title: 'Distributed Systems & Go Concurrency Clinic',
    description: 'Working through Raft consensus edge cases and channel deadlocks. Come peer-review or debug together!',
    roomCode: 'RAFT-904',
    initiator: mockUsers[1],
    participants: [mockUsers[1], mockUsers[5]],
    status: 'ACTIVE',
    codingLanguage: 'Go',
    currentActivity: 'Benchmarking Raft heartbeat timeouts',
    problem: mockProblems[6],
    createdAt: new Date(Date.now() - 3600000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'room-2',
    title: 'Interactive Shader Canvas Workshop',
    description: 'Creating smooth particle effects with Three.js & GLSL. Beginners & designers warmly welcome!',
    roomCode: 'SHDR-302',
    initiator: mockUsers[2],
    participants: [mockUsers[2]],
    status: 'ACTIVE',
    codingLanguage: 'JavaScript',
    currentActivity: 'Writing GLSL fragment noise function',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'room-3',
    title: 'Daily LeetCode Hard Sprint',
    description: 'Speed-solving Graph Algorithms & DP problems. Sharing hints and optimal code architectures.',
    roomCode: 'DSA-771',
    initiator: mockUsers[0],
    participants: [mockUsers[0], mockUsers[4]],
    status: 'ACTIVE',
    codingLanguage: 'TypeScript',
    currentActivity: 'Solving Median of Two Sorted Arrays',
    problem: mockProblems[8],
    createdAt: new Date(Date.now() - 2400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// ============================================================
// CONNECTIONS (backend Connection model)
// ============================================================
export const mockConnections: Connection[] = [
  {
    id: 'conn-1',
    requesterId: '1',
    requester: mockUsers[0],
    addresseeId: '2',
    addressee: mockUsers[1],
    status: 'ACCEPTED',
    message: 'Hey Alex, loved your talk on Kafka streaming patterns! Would love to connect.',
    createdAt: new Date('2024-10-15').toISOString(),
    updatedAt: new Date('2024-10-15').toISOString(),
  },
  {
    id: 'conn-2',
    requesterId: '1',
    requester: mockUsers[0],
    addresseeId: '3',
    addressee: mockUsers[2],
    status: 'ACCEPTED',
    message: 'Hi Emma! Inspiring work on design systems.',
    createdAt: new Date('2024-10-20').toISOString(),
    updatedAt: new Date('2024-10-20').toISOString(),
  },
  {
    id: 'conn-3',
    requesterId: '5',
    requester: mockUsers[4],
    addresseeId: '1',
    addressee: mockUsers[0],
    status: 'ACCEPTED',
    message: 'Hey Sarah! Working on cross-platform bridges, excited to exchange ideas.',
    createdAt: new Date('2024-11-05').toISOString(),
    updatedAt: new Date('2024-11-05').toISOString(),
  },
  {
    id: 'conn-4',
    requesterId: '4',
    requester: mockUsers[3],
    addresseeId: '1',
    addressee: mockUsers[0],
    status: 'PENDING',
    message: 'Hey Sarah, would love to collaborate on deploying local LLM fine-tunes in Next.js web applications!',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'conn-5',
    requesterId: '6',
    requester: mockUsers[5],
    addresseeId: '1',
    addressee: mockUsers[0],
    status: 'PENDING',
    message: 'Hi! Saw your TypeScript compiler architecture post. Let us connect and discuss Rust-Wasm bindings.',
    createdAt: new Date(Date.now() - 18000000).toISOString(),
    updatedAt: new Date(Date.now() - 18000000).toISOString(),
  },
];

// Suggested developers for connection
export const mockSuggestedDevelopers = [
  {
    user: mockUsers[5],
    mutualConnections: 3,
    matchReason: 'Shares skills: TypeScript, Docker & Systems Design',
    matchPercentage: 94,
  },
  {
    user: mockUsers[6],
    mutualConnections: 2,
    matchReason: 'Both active in Security & High Performance Algorithms',
    matchPercentage: 88,
  },
  {
    user: mockUsers[3],
    mutualConnections: 4,
    matchReason: 'Rank #4 developer in your peer group',
    matchPercentage: 91,
  },
];

// ============================================================
// CONVERSATIONS & MESSAGES (backend ChatService with CODE types)
// ============================================================
export const mockConversations: Conversation[] = [
  {
    id: 'conv-1',
    type: 'DIRECT',
    participants: [mockUsers[0], mockUsers[1]],
    lastMessage: {
      id: 'msg-105',
      senderId: '2',
      sender: mockUsers[1],
      receiverId: '1',
      receiver: mockUsers[0],
      content: 'Here is the atomic cache lock implementation using Redis SETNX with lease renewal:',
      type: 'CODE',
      codeLanguage: 'go',
      media: `func AcquireLock(ctx context.Context, client *redis.Client, key string, ttl time.Duration) (string, error) {
    token := uuid.New().String()
    ok, err := client.SetNX(ctx, "lock:"+key, token, ttl).Result()
    if err != nil || !ok {
        return "", ErrLockBusy
    }
    return token, nil
}`,
      isRead: false,
      isEdited: false,
      createdAt: new Date(Date.now() - 600000).toISOString(),
      updatedAt: new Date(Date.now() - 600000).toISOString(),
    },
    unreadCount: 1,
    createdAt: new Date('2024-10-15').toISOString(),
    updatedAt: new Date(Date.now() - 600000).toISOString(),
  },
  {
    id: 'conv-2',
    type: 'DIRECT',
    participants: [mockUsers[0], mockUsers[2]],
    lastMessage: {
      id: 'msg-203',
      senderId: '3',
      sender: mockUsers[2],
      receiverId: '1',
      receiver: mockUsers[0],
      content: 'Check out this smooth CSS glassmorphism border animation! Works flawlessly in Safari too 🎉',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    unreadCount: 0,
    createdAt: new Date('2024-10-20').toISOString(),
    updatedAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'conv-3',
    type: 'GROUP',
    name: '🚀 Systems & Algorithms Elite',
    participants: [mockUsers[0], mockUsers[1], mockUsers[2], mockUsers[5]],
    lastMessage: {
      id: 'msg-308',
      senderId: '6',
      sender: mockUsers[5],
      content: 'Who is ready for the weekend algorithm contest? Target is sub-100ms runtime for graph queries!',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 14400000).toISOString(),
      updatedAt: new Date(Date.now() - 14400000).toISOString(),
    },
    unreadCount: 0,
    createdAt: new Date('2024-11-01').toISOString(),
    updatedAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'conv-4',
    type: 'DIRECT',
    participants: [mockUsers[0], mockUsers[4]],
    lastMessage: {
      id: 'msg-401',
      senderId: '5',
      sender: mockUsers[4],
      receiverId: '1',
      receiver: mockUsers[0],
      content: 'Thanks for the peer review on the cross-platform memory leaks issue!',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 86400000).toISOString(),
      updatedAt: new Date(Date.now() - 86400000).toISOString(),
    },
    unreadCount: 0,
    createdAt: new Date('2024-11-10').toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const mockMessagesByConversation: Record<string, Message[]> = {
  'conv-1': [
    {
      id: 'msg-101',
      senderId: '1',
      sender: mockUsers[0],
      content: 'Hey Alex! Did you manage to test the Redis clustering failover scenario under load?',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
      id: 'msg-102',
      senderId: '2',
      sender: mockUsers[1],
      content: 'Yes! We saw a 350ms blip during sentinel master re-election, but circuit breakers caught 99% of requests.',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 5400000).toISOString(),
      updatedAt: new Date(Date.now() - 5400000).toISOString(),
    },
    {
      id: 'msg-103',
      senderId: '1',
      sender: mockUsers[0],
      content: 'Awesome. What mechanism are you using for distributed lock renewal?',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 3600000).toISOString(),
      updatedAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
      id: 'msg-104',
      senderId: '2',
      sender: mockUsers[1],
      content: 'Here is the atomic cache lock implementation using Redis SETNX with lease renewal:',
      type: 'CODE',
      codeLanguage: 'go',
      media: `func AcquireLock(ctx context.Context, client *redis.Client, key string, ttl time.Duration) (string, error) {
    token := uuid.New().String()
    ok, err := client.SetNX(ctx, "lock:"+key, token, ttl).Result()
    if err != nil || !ok {
        return "", ErrLockBusy
    }
    // Launch renewal heartbeat goroutine
    go renewLock(ctx, client, key, token, ttl)
    return token, nil
}`,
      isRead: false,
      isEdited: false,
      createdAt: new Date(Date.now() - 600000).toISOString(),
      updatedAt: new Date(Date.now() - 600000).toISOString(),
    },
  ],
  'conv-2': [
    {
      id: 'msg-201',
      senderId: '1',
      sender: mockUsers[0],
      content: 'Emma, love the fluid glass components on the new explore page!',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 14400000).toISOString(),
      updatedAt: new Date(Date.now() - 14400000).toISOString(),
    },
    {
      id: 'msg-202',
      senderId: '3',
      sender: mockUsers[2],
      content: 'Thank you Sarah! Added subtle backdrop blur and border gradients for that extra modern polish.',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 10800000).toISOString(),
      updatedAt: new Date(Date.now() - 10800000).toISOString(),
    },
    {
      id: 'msg-203',
      senderId: '3',
      sender: mockUsers[2],
      content: 'Check out this smooth CSS glassmorphism border animation! Works flawlessly in Safari too 🎉',
      type: 'TEXT',
      isRead: true,
      isEdited: false,
      createdAt: new Date(Date.now() - 7200000).toISOString(),
      updatedAt: new Date(Date.now() - 7200000).toISOString(),
    },
  ],
};

// ============================================================
// NOTIFICATIONS (matching backend NotificationsService enum)
// ============================================================
export const mockNotifications: Notification[] = [
  {
    id: 'notif-1',
    userId: '1',
    type: 'CONNECTION_REQUEST',
    title: 'New Connection Request',
    message: 'Michael Zhang sent you a connection request: "Would love to collaborate on local LLM apps"',
    link: '/connections',
    sender: mockUsers[3],
    isRead: false,
    entityType: 'CONNECTION',
    entityId: 'conn-4',
    createdAt: new Date(Date.now() - 1800000).toISOString(),
  },
  {
    id: 'notif-2',
    userId: '1',
    type: 'ACHIEVEMENT_UNLOCKED',
    title: '🏆 Grandmaster Rank #1 Achieved!',
    message: 'You have claimed the #1 spot on the Global Leaderboard with 15,420 XP! You earned the Architect Badge.',
    link: '/leaderboard',
    isRead: false,
    entityType: 'ACHIEVEMENT',
    entityId: 'ach-1',
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'notif-3',
    userId: '1',
    type: 'POST_REACTION',
    title: 'Alex Kumar loved your post',
    message: 'Alex Kumar and 14 others reacted to "Real-time collaborative code editor architecture"',
    link: '/explore',
    sender: mockUsers[1],
    isRead: false,
    entityType: 'POST',
    entityId: 'post-1',
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: 'notif-4',
    userId: '1',
    type: 'POST_COMMENT',
    title: 'New comment on your post',
    message: 'Emma Rodriguez commented: "The WebAssembly memory layout explanation was pure gold 🔥"',
    link: '/explore',
    sender: mockUsers[2],
    isRead: true,
    entityType: 'COMMENT',
    entityId: 'comm-1',
    createdAt: new Date(Date.now() - 28800000).toISOString(),
  },
  {
    id: 'notif-5',
    userId: '1',
    type: 'COLLABORATION_REQUEST',
    title: 'Live Pair Programming Invite',
    message: 'David Lindqvist invited you to join "Daily LeetCode Hard Sprint" in room #DSA-771',
    link: '/live',
    sender: mockUsers[5],
    isRead: true,
    entityType: 'COLLABORATION',
    entityId: 'room-3',
    createdAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: 'notif-6',
    userId: '1',
    type: 'CODING_CHALLENGE',
    title: 'Daily Streak Bonus (+50 XP)',
    message: 'Your 45-day coding streak is intact! Solve today\'s featured problem to keep the flame alive.',
    link: '/problems/implement-debounce',
    isRead: true,
    entityType: 'STREAK',
    createdAt: new Date(Date.now() - 86400000).toISOString(),
  },
];

// ============================================================
// SUBMISSIONS & ACTIVITY (backend Submission & XpTransaction)
// ============================================================
export const mockSubmissions: Submission[] = [
  {
    id: 'sub-101',
    problemId: '1',
    problemTitle: 'Two Sum',
    problem: mockProblems[0],
    userId: '1',
    user: mockUsers[0],
    language: 'TypeScript',
    code: `function twoSum(nums: number[], target: number): number[] {
  const map = new Map<number, number>();
  for (let i = 0; i < nums.length; i++) {
    const diff = target - nums[i];
    if (map.has(diff)) return [map.get(diff)!, i];
    map.set(nums[i], i);
  }
  return [];
}`,
    status: 'ACCEPTED',
    runtime: 54, // ms
    memory: 44.2, // MB
    testCasesPassed: 63,
    totalTestCases: 63,
    score: 100,
    xpEarned: 10,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'sub-102',
    problemId: '4',
    problemTitle: 'Maximum Subarray (Kadane)',
    problem: mockProblems[3],
    userId: '1',
    user: mockUsers[0],
    language: 'Go',
    code: `func maxSubArray(nums []int) int {
    maxSum := nums[0]
    curSum := nums[0]
    for i := 1; i < len(nums); i++ {
        if curSum < 0 {
            curSum = nums[i]
        } else {
            curSum += nums[i]
        }
        if curSum > maxSum {
            maxSum = curSum
        }
    }
    return maxSum
}`,
    status: 'ACCEPTED',
    runtime: 78,
    memory: 28.6,
    testCasesPassed: 209,
    totalTestCases: 209,
    score: 100,
    xpEarned: 20,
    createdAt: new Date(Date.now() - 18000000).toISOString(),
  },
  {
    id: 'sub-103',
    problemId: '8',
    problemTitle: 'LRU Cache Implementation',
    problem: mockProblems[7],
    userId: '1',
    user: mockUsers[0],
    language: 'TypeScript',
    status: 'TIME_LIMIT_EXCEEDED',
    runtime: 2150,
    memory: 68.4,
    testCasesPassed: 18,
    totalTestCases: 22,
    score: 81,
    error: 'Time Limit Exceeded on large test case 19 (100,000 get/put operations)',
    xpEarned: 5,
    createdAt: new Date(Date.now() - 48000000).toISOString(),
  },
  {
    id: 'sub-104',
    problemId: '10',
    problemTitle: 'Custom Promise.allSettled Polyfill',
    problem: mockProblems[9],
    userId: '1',
    user: mockUsers[0],
    language: 'JavaScript',
    status: 'ACCEPTED',
    runtime: 62,
    memory: 41.8,
    testCasesPassed: 40,
    totalTestCases: 40,
    score: 100,
    xpEarned: 25,
    createdAt: new Date(Date.now() - 96000000).toISOString(),
  },
];

export const mockActivityFeed: ActivityFeedItem[] = [
  {
    id: 'act-1',
    type: 'SUBMISSION',
    title: 'Solved "Two Sum" with 100% test pass',
    description: 'Submitted optimal O(N) Hash Table approach in TypeScript. Beat 94% in runtime.',
    timestamp: '1 hour ago',
    xpEarned: 10,
    status: 'ACCEPTED',
  },
  {
    id: 'act-2',
    type: 'COLLABORATION',
    title: 'Completed Live Pair Session with Alex Kumar',
    description: 'Collaborated for 45 minutes on Raft Consensus protocol and high-concurrency benchmarks.',
    timestamp: '4 hours ago',
    xpEarned: 35,
    status: 'COMPLETED',
  },
  {
    id: 'act-3',
    type: 'ACHIEVEMENT',
    title: 'Unlocked "Algorithm Architect" Achievement',
    description: 'Solved over 250 problems across Data Structures & Algorithms categories.',
    timestamp: 'Yesterday',
    xpEarned: 150,
  },
  {
    id: 'act-4',
    type: 'STREAK',
    title: 'Reached 45-Day Coding Streak! 🔥',
    description: 'Consistency pays off! Streak multiplier upgraded to 1.5x XP.',
    timestamp: 'Yesterday',
    xpEarned: 50,
  },
  {
    id: 'act-5',
    type: 'POST',
    title: 'Published tech breakdown: "Real-time WebSockets with OT"',
    description: 'Article received 24 reactions, 8 comments, and 3 community shares.',
    timestamp: '2 days ago',
    xpEarned: 20,
  },
];

// ============================================================
// SAVED CONTENT (Bookmarks matching backend entities)
// ============================================================
export const mockSavedItems: SavedItem[] = [
  {
    id: 'saved-1',
    type: 'PROBLEM',
    title: 'Design Scalable Rate Limiter',
    description: 'Distributed rate limiter using Redis Token Bucket & Sliding Window. Bookmark for upcoming System Design interviews.',
    category: 'System Design',
    tags: ['Redis', 'Distributed Systems', 'Hard'],
    link: '/problems/design-rate-limiter',
    problem: mockProblems[6],
    savedAt: 'Saved 2 days ago',
  },
  {
    id: 'saved-2',
    type: 'PROBLEM',
    title: 'LRU Cache Implementation',
    description: 'Double linked list + HashMap O(1) eviction logic. Revisit and optimize memory usage.',
    category: 'DSA',
    tags: ['Linked List', 'Hash Table', 'Hard'],
    link: '/problems/lru-cache',
    problem: mockProblems[7],
    savedAt: 'Saved 3 days ago',
  },
  {
    id: 'saved-3',
    type: 'POST',
    title: 'Microservices Monitoring Dashboard with Prometheus & Grafana',
    description: 'Architecture breakdown by Alex Kumar on lightweight metrics visualization in Kubernetes.',
    category: 'Architecture',
    tags: ['DevOps', 'Kubernetes', 'Backend'],
    link: '/explore',
    savedAt: 'Saved 4 days ago',
  },
  {
    id: 'saved-4',
    type: 'SNIPPET',
    title: 'Distributed Redis Lock with Auto-Renewal',
    description: 'Production-ready Go lock helper with context cancellation and heartbeat lease renewal.',
    category: 'Code Snippet',
    tags: ['Go', 'Redis', 'Concurrency'],
    link: '/messages',
    codeSnippet: {
      language: 'go',
      code: `func AcquireLock(ctx context.Context, client *redis.Client, key string, ttl time.Duration) (string, error) {
    token := uuid.New().String()
    ok, err := client.SetNX(ctx, "lock:"+key, token, ttl).Result()
    if err != nil || !ok {
        return "", ErrLockBusy
    }
    return token, nil
}`,
    },
    savedAt: 'Saved 5 days ago',
  },
  {
    id: 'saved-5',
    type: 'DEVELOPER',
    title: 'David Lindqvist',
    description: 'Principal Systems Architect working on Rust, WebAssembly and eBPF kernel network stacks.',
    category: 'Developer Profile',
    tags: ['Rust', 'Systems', 'Wasm'],
    link: '/profile/dlindqvist',
    user: mockUsers[5],
    savedAt: 'Saved 1 week ago',
  },
];

// ============================================================
// ACHIEVEMENTS (backend Achievement model)
// ============================================================
export const mockAchievements: Achievement[] = [
  {
    id: 'ach-1',
    name: 'Top Grandmaster #1',
    description: 'Achieve and hold the Rank #1 position on the Global Community Leaderboard',
    icon: '👑',
    category: 'Rankings',
    xpReward: 500,
    isUnlocked: true,
    earnedAt: '2024-11-20',
  },
  {
    id: 'ach-2',
    name: 'Streak Master 45',
    description: 'Maintain an active coding streak for 45 consecutive days',
    icon: '🔥',
    category: 'Dedication',
    xpReward: 300,
    isUnlocked: true,
    earnedAt: '2024-11-26',
  },
  {
    id: 'ach-3',
    name: 'Algorithm Polyglot',
    description: 'Solve problems in at least 4 distinct programming languages (TS, Go, Python, Java)',
    icon: '🌐',
    category: 'Versatility',
    xpReward: 250,
    isUnlocked: true,
    earnedAt: '2024-10-15',
  },
  {
    id: 'ach-4',
    name: 'Peer Collaboration Pro',
    description: 'Participate in 25 live collaborative code rooms with fellow developers',
    icon: '🤝',
    category: 'Community',
    xpReward: 200,
    isUnlocked: false,
    progress: 19,
    maxProgress: 25,
  },
  {
    id: 'ach-5',
    name: 'Hard Problem Crusher',
    description: 'Successfully solve 50 Hard or Expert level problems with clean tests',
    icon: '⚡',
    category: 'Mastery',
    xpReward: 400,
    isUnlocked: false,
    progress: 38,
    maxProgress: 50,
  },
  {
    id: 'ach-6',
    name: 'Bug Hunter Extraordinaire',
    description: 'Find and optimize 15 edge case solutions submitted in community code reviews',
    icon: '🐛',
    category: 'Quality',
    xpReward: 150,
    isUnlocked: true,
    earnedAt: '2024-09-12',
  },
];

// Mock Posts (matching backend Post + PostType)
export const mockPosts: Post[] = [
  {
    id: '1',
    content:
      'Just completed our new real-time collaborative coding engine powered by WebSockets and CRDTs! 🚀\n\nKey architectural pillars:\n• Optimistic local state updates with conflict-free replication\n• Socket.IO channels partitioned by problem room ID\n• Sub-20ms latency over edge worker endpoints\n\nDrop a comment if you are building collaborative dev tools or want to test it together!',
    authorId: '1',
    author: mockUsers[0],
    visibility: 'PUBLIC',
    tags: ['WebSockets', 'React', 'Distributed Systems', 'Architecture'],
    reactionCount: 56,
    commentCount: 18,
    shareCount: 9,
    reactions: [],
    createdAt: new Date(Date.now() - 14400000).toISOString(),
    updatedAt: new Date(Date.now() - 14400000).toISOString(),
  },
  {
    id: '2',
    content:
      'Excited to open-source our microservices telemetry bridge for Kubernetes clusters! 📊\n\nStack breakdown:\n• Go / Spring Boot service meshes\n• Prometheus vector metrics pipeline\n• Grafana dynamic dashboard templates\n\nGitHub repo is live. Contributions on high-cardinality label indexing are very welcome!',
    authorId: '2',
    author: mockUsers[1],
    visibility: 'PUBLIC',
    tags: ['Microservices', 'Kubernetes', 'Go', 'DevOps'],
    reactionCount: 42,
    commentCount: 15,
    shareCount: 12,
    reactions: [],
    createdAt: new Date(Date.now() - 43200000).toISOString(),
    updatedAt: new Date(Date.now() - 43200000).toISOString(),
  },
  {
    id: '3',
    content:
      'CSS Tip: Modern fluid typography without media queries! 💡\n\n```css\nfont-size: clamp(1.125rem, 0.95rem + 0.85vw, 1.75rem);\n```\n\nScales seamlessly across ultra-wide 4K monitors down to mobile viewports without breakpoint jumps. Combined with container queries, it changes everything!',
    authorId: '3',
    author: mockUsers[2],
    visibility: 'PUBLIC',
    tags: ['CSS', 'Frontend', 'Design Systems', 'WebDev'],
    reactionCount: 89,
    commentCount: 27,
    shareCount: 34,
    reactions: [],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: '4',
    content:
      'Benchmark results from fine-tuning small LLMs on domain codebases:\n\nA 7B quantized model specifically fine-tuned on AST syntax patterns achieved 88% pass@1 on synthetic unit test generation, matching GPT-4-mini while running 100% locally on an M3 Max!\n\nLocal AI for private enterprise code is officially here.',
    authorId: '4',
    author: mockUsers[3],
    visibility: 'PUBLIC',
    tags: ['AI', 'Python', 'MachineLearning', 'LLM'],
    reactionCount: 64,
    commentCount: 21,
    shareCount: 19,
    reactions: [],
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    updatedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];
